### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by di48l069** [Chocobozzz/OpenVPN-Admin#62]
Hi,

Please can someone provide me with a clear description on how to install `OpenVPN-Admin`

Like a step by step process on all requirements Apache etc

the process in README is not very clear to me as i'm new to using any form of linux and  also you dont state that the user must be root or must create new user would be cool if you can note this down below please 

like how would you do this 

> Setup the web server (Apache, NGinx...) to serve the web application.

**Comment by SansPseudoFix** [comment]
Hi, sorry but you have **plenty of** howtos ([apache2](https://www.digitalocean.com/community/tutorials/how-to-configure-the-apache-web-server-on-an-ubuntu-or-debian-vps) or [nginx](https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-16-04) - 2 seconds search) on Internet to figure out how to set up a web server.

We provide an easy way to install OpenVPN, but not an easy way to set up a server. You have to lean it before (otherwise, it can be dangerous for your users/datas etc).
